### PR TITLE
fix: handle frame manager init without unhandled rejection

### LINKED ISSUE #10892: [Bug]: Errors thrown after doing history restoration on page with oopifs/workers
### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer';

const browser = await puppeteer.launch({
  headless: false,
  defaultViewport: null,
  ignoreDefaultArgs: ['--enable-automation'],
  executablePath: process.env.CHROME_PATH,
});
const page = await browser.newPage();
const session = await page.target().createCDPSession();

await session.send('Page.enable');

await page.goto('http://localhost:10200/oopif-scripts.html', {
  waitUntil: ['networkidle0'],
});

await new Promise(r => setTimeout(r, 500));

const history = await session.send('Page.getNavigationHistory');
const entry = history.entries[history.currentIndex];

await session.send('Page.navigate', {url: 'chrome://terms'});

await new Promise(r => setTimeout(r, 500));

await session.send('Page.navigateToHistoryEntry', {entryId: entry.id});

await session.send('Page.disable');

await page.close();
await browser.close();
```

### Error string

Protocol error (Network.enable): Target closed

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

This is a minified version of how Lighthouse tests the bfcache: https://github.com/GoogleChrome/lighthouse/blob/main/core/gather/gatherers/bf-cache-failures.js#L89

The latest release of puppeteer (21.2.0) has broken this behavior on our test page [`oopif-scripts.html`](https://github.com/GoogleChrome/lighthouse/blob/main/cli/test/fixtures/oopif-scripts.html). All the code needed to serve this test page can be found under the `fixtures` directory that contains `oopif-scripts.html`.

### Expectation

I expected the code to run without throwing any errors or emitting uncaught exceptions. I verified that this is still the behavior for version 21.1.1.

### Reality

The script throws an error.

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

21.2.0

### Node version

18.17.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #10892

### CODE REVIEW

File: packages/puppeteer-core/src/common/FrameManager.ts [hunk 1]
```diff
@@ -239,13 +239,11 @@ export class FrameManager extends EventEmitter<FrameManagerEvents> {
   async initialize(client: CDPSession): Promise<void> {
     try {
       const networkInit = this.#networkManager.addClient(client);
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/common/FrameManager.ts]: Nit this can be moved inside the `Promise.all` as well.

**Review by Lightning00Blade — APPROVED** [review]
