### PR TITLE
fix: type page event listeners correctly

### LINKED ISSUE #6854: puppeteer.HTTPRequest resourceType() returns string instead of a resource type enum
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.4
* Platform / OS version: Mac
* URLs (if applicable): n/a
* Node.js version: v10

I want to ask about difference while migrating from `@types/puppeteer` to the included definitions (thank you btw!)

In the past (with DefinitelyTyped), request resource types were defined ("document", "xhr", etc.):

```
page.on("request", request => {
   const resourceType = request.resourceType(); // puppeteer.ResourceType
});
```

Now, it returns `string`. I see there is a `puppeteer.Protocol.Network.ResourceType` (although those are not lowercased). 

Is there a type we can use for this instead of `string`? Same for `request.method()` which also now returns `string` instead of the old DefinitelyTyped `puppeteer.HttpMethod`.

Thank you!

### PR DESCRIPTION
**Pull request by jackfranklin**
This PR fixes the fact that currently if you have:

```ts
page.on('request', request => {

})
```

Then `request` will be typed as `any`. We can fix this by defining an
interface of event name => callback argument type, and looking that up
when you call `page.on`.

Fixes #6854.

### CODE REVIEW

**Review by mathiasbynens — APPROVED** [review]

File: src/common/HTTPRequest.ts [hunk 1]
```diff
@@ -40,7 +40,10 @@ export interface ContinueRequestOverrides {
  */
 export interface ResponseForRequest {
   status: number;
-  headers: Record<string, string>;
+  /**
+   * Optional response headers. All values are converted to strings.
+   */
+  headers: Record<string, any>;
```
Comment (jschfflr) [inline src/common/HTTPRequest.ts]: Why did you change this to any?

File: src/common/Page.ts [hunk 2]
```diff
@@ -329,6 +329,34 @@ export const enum PageEmittedEvents {
...
+  load: never;
+  metrics: { title: string; metrics: Metrics };
+  pageerror: Error;
+  popup: Page;
+  request: HTTPRequest;
+  response: HTTPResponse;
+  requestfailed: HTTPRequest;
+  requestfinished: HTTPRequest;
+  workercreated: WebWorker;
+  workerdestroyed: WebWorker;
```
Comment (jschfflr) [inline src/common/Page.ts:358]: What about adding a [event: string]: any at the bottom here to make sure we don't break places that use other event names? Or is that intended?

File: src/common/HTTPRequest.ts (hunk 1 above)
Comment (jackfranklin) [reply src/common/HTTPRequest.ts]: Good point, not sure. I think we stringify them anyway so `unknown` is better here.

File: src/common/Page.ts (hunk 2 above)
Comment (jackfranklin) [reply src/common/Page.ts:358]: I'd rather it fail explicitly because we're missing a type.
