### PR TITLE
fix: make `Target.asPage` return the same Page instance

### LINKED ISSUE #14843: [Bug]: Target.asPage returns different instance each call
### Minimal, reproducible example

```TypeScript
const browser = await puppeteer.launch();
  try {
    const page = await browser.newPage();

    const target = page.target();

    const page1 = await target.asPage();
    const page2 = await target.asPage();

    console.log('page1 === page2:', page1 === page2);
    // expected: true, actual: false
  } finally {
    await browser.close();
  }
```

### Background

_No response_

### Expectation

the `.asPage()` method always return the same `Page` instance for a specific `Target`.

### Reality

the `.asPage()` method returns 2 different `Page` instances for the same `Target`.

### Puppeteer configuration file (if used)

```TypeScript

```

### Puppeteer version

latest

### Node version

v24.14.0

### Package manager

npm

### Package manager version

11.9.0

### Operating system

macOS

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Closes https://github.com/puppeteer/puppeteer/pull/14860
Fixes https://github.com/puppeteer/puppeteer/issues/14843

### CODE REVIEW

File: packages/puppeteer-core/src/bidi/Page.ts [hunk 1]
```diff
@@ -671,8 +672,12 @@ export class BidiPage extends Page {
     throw new UnsupportedOperation();
   }
 
-  override target(): never {
-    throw new UnsupportedOperation();
+  override target(): Target {
+    const target = this.browserContext().getTargetForPage(this);
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/bidi/Page.ts:676]: I am not sure why we didn't expose this previously, let me know if I should revert this part and add test expectations for this not working with BiDi

File: packages/puppeteer-core/src/bidi/BrowserContext.ts [hunk 2]
```diff
@@ -187,6 +187,13 @@ export class BidiBrowserContext extends BrowserContext {
     });
   }
```
Comment (abiiget765) [inline packages/puppeteer-core/src/bidi/BrowserContext.ts]: [CI](https://github.com/puppeteer/puppeteer/actions/workflows/ci.yml)

File: packages/puppeteer-core/src/bidi/Page.ts (hunk 1 above)
Comment (OrKoN) [reply packages/puppeteer-core/src/bidi/Page.ts:676]: I think we though about deprecating and removing the target API altogether. But I am not sure it is going to happen any time soon.

**Review by OrKoN — APPROVED** [review]
