### PR TITLE
fix(Frame): postpone evaluations until execution context gets created

### LINKED ISSUE #827: frame.title() throws protocol error when used with framenavigated
Repro: 

```js
const browser = await puppeteer.launch();
const page = await browser.newPage();

page.on('framenavigated', async frame => {
  console.log(await frame.title());
  browser.close();  
});

await page.goto('https://example.com');
```

Produces:

```
Error: Protocol error (Runtime.evaluate): Cannot find context with specified id undefined
```

### PR DESCRIPTION
**Pull request by aslushnikov**
In Blink, frames don't necesserily have execution context all the time.
DevTools Protocol precisely reports this situation, which results in
Puppeteer's frame.executionContext() being null occasionally.

However, from puppeteer point of view every frame will have at least a
default executions context, sooner or later:
- frame's execution context might be created naturally to run frame's
  javascript
- if frame has no javascript, devtools protocol will issue execution
  context creation

This patch builds up on this assumption and makes `frame.executionContext()`
to be a promise.
As a result, all the evaluations await for the execution context to be created first.

Fixes #827, #1325 

BREAKING CHANGE: this patch changes `frame.executionContext()` method to return a promise.
To migrate onto a new behavior, await the context first before using it.

### CODE REVIEW

File: lib/ExecutionContext.js [hunk 1]
```diff
@@ -19,12 +19,16 @@ const {helper} = require('./helper');
...
+   * @param {!Object} contextPayload
    * @param {function(*):!JSHandle} objectHandleFactory
    */
-  constructor(client, contextId, objectHandleFactory) {
+  constructor(client, contextPayload, objectHandleFactory) {
     this._client = client;
-    this._contextId = contextId;
+    this._contextId = contextPayload.id;
+
+    const auxData = contextPayload.auxData || {};
```
Comment (dgozman) [inline lib/ExecutionContext.js]: .. || {isDefault: true}

File: utils/doclint/check_public_api/index.js [hunk 2]
```diff
@@ -28,7 +28,6 @@ const EXCLUDE_CLASSES = new Set([
   'Multimap',
   'NavigatorWatcher',
   'NetworkManager',
-  'ProxyStream',
```
Comment (dgozman) [inline utils/doclint/check_public_api/index.js:31]: Unrelated?

**Review by dgozman — APPROVED** [review]

File: lib/ExecutionContext.js (hunk 1 above)
Comment (aslushnikov) [reply lib/ExecutionContext.js]: Thanks, that's a nice one.

File: utils/doclint/check_public_api/index.js (hunk 2 above)
Comment (aslushnikov) [reply utils/doclint/check_public_api/index.js:31]: That's a drive-by
