### PR TITLE
fix: standardize error handling for closed connections

### LINKED ISSUE #14123: [Bug]: Connection.ts throws plain Error instead of ProtocolError
### Minimal, reproducible example

https://github.com/puppeteer/puppeteer/blob/main/packages/puppeteer-core/src/cdp/Connection.ts#L134

What the hell??

Image

### Background

_No response_

### Expectation

Should throw ProtocolError

### Reality

Throws plain Error with "Protocol error" message. 

### Puppeteer configuration file (if used)

```TypeScript

```

### Puppeteer version

24.16.2

### Node version

22

### Package manager

yarn

### Package manager version

4

### Operating system

macOS

### PR DESCRIPTION
**Pull request by OrKoN**
Adds ConnectionClosedError class.

Closes https://github.com/puppeteer/puppeteer/issues/14123

### CODE REVIEW

File: packages/puppeteer-core/src/bidi/Connection.ts [hunk 1]
```diff
@@ -100,8 +100,9 @@ export class BidiConnection
     params: Commands[T]['params'],
     timeout?: number,
   ): Promise<{result: Commands[T]['returnType']}> {
-    assert(!this.#closed, 'Protocol error: Connection closed.');
-
+    if (this.#closed) {
+      return Promise.reject(new Error('Connection closed.'));
```
Comment (OrKoN) [inline packages/puppeteer-core/src/bidi/Connection.ts]: I am thinking if it makes sense to create a dedicated error subclass for ConnectionErrors?

Comment (OrKoN) [reply packages/puppeteer-core/src/bidi/Connection.ts]: I think we should

**Review by Lightning00Blade — APPROVED** [review]
