### PR TITLE
fix(page): Page.goto should properly handle historyAPI in beforeunload

### LINKED ISSUE #2764: Some URLs sequence makes next responses to be null
* Puppeteer version: 1.5.0-post (chromium_revision 567388)
* Platform / OS version: Windows 7 x64
* URLs (if applicable): see in the example
* Node.js version: 10.4.1

I have a script that validates links. Sometimes, after getting some URL, all next responses become `null`.

I've managed to reduce the issue to this case:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch();
    const [page] = await browser.pages();

    let response = await page.goto('https://twitter.com/');
    console.log(response ? response.status() : response);
    response = await page.goto('https://github.com/nodejs/node');
    console.log(response ? response.status() : response);
    response = await page.goto('https://github.com/GoogleChrome/puppeteer/');
    console.log(response ? response.status() : response);

    await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

**What is the expected result?**
```
200
200
200
```

**What happens instead?**
```
200
null
null
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Protocol's `page.navigate` doesn't report loaderId if the command resulted in a same-document
navigation. In this case we should anticipate same-document navigation and otherwise we should
wait for new document navigation.

Fixes #2764.

### CODE REVIEW

File: lib/Page.js [hunk 1]
```diff
@@ -644,7 +649,11 @@ class Page extends EventEmitter {
 
     const responses = new Map();
     const listener = helper.addEventListener(this._networkManager, NetworkManager.Events.Response, response => responses.set(response.url(), response));
-    const error = await watcher.navigationPromise();
+    const error = await Promise.race([
+      watcher.timeoutPromise(),
```
Comment (JoelEinbinder) [inline lib/Page.js:653]: why await the timeout promise here? Won't the same and new document navigations be called with the timeout?

Comment (aslushnikov) [reply lib/Page.js:653]: no, I split them out (see NavigationWatcher)

**Review by JoelEinbinder — APPROVED** [review]

**Comment by ntzm** [comment]
It's me again :D Will this fix #2479?

**Comment by aslushnikov** [comment]
@ntzm ah sorry, I still can repro this on tip-of-tree. Let me look into this; i forgot what was the root cause.

**Comment by ntzm** [comment]
No worries, sorry to keep bothering you :D
