### PR TITLE
fix: close chrome gracefully with Browser.close

### LINKED ISSUE #921: userDataDir + headless = lost authorization
* Puppeteer version: v0.12.0-alpha
* Platform / OS version: Windows 7 x64
* URLs (if applicable): any that needs authorization

1. Create a test script and an empty folder `test-profile-dir`:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: false,
      userDataDir: 'test-profile-dir',
    });
    const page = await browser.newPage();

    await page.goto('https://twitter.com/');

    console.log(await page.evaluate(() => document.title));
    console.log(await page.evaluate(() => document.cookie));

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
You will see something like this:
```console
Twitter. It's what's happening.

personalization_id=...; guest_id=...; ct0=...
```
Sign in into Twitter and close the browser.

2. Run the same script second time (`await browser.close();` can be uncommented). You will see something like this:
```console
Twitter

personalization_id=...; guest_id=...; ct0=...; ads_prefs=...; remember_checked_on=...;
twid=...; tip_nightmode=...; _ga=...; _gid=...; dnt=...; lang=...
```
3. Run the same script, but with `headless: true,` The output is the same as before authorization:
```console
Twitter. It's what's happening.

personalization_id=...; guest_id=...; ct0=...
```

I have tried various sites, all of them seem to lose authorization in headless mode.

Some more notes:

* `response.request().headers` does not contain cookies in both `headless: false` and `headless: true` modes.

* `console.log(await page.cookies('https://twitter.com/'));` contains many cookies in the `headless: false` mode. In the `headless: true` mode it gives an empty array `[]`.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
`browser.close()` now closes the browser, regardless of whether or not it was created with `puppeteer.launch()` or `puppeteer.connect()`
#989

`browser.disconnect()` is a new method which disconnects Puppeteer from the browser, but does not close the Chromium process.

Should fix #921 and #918

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
@vsemozhetbyt @elisherer does this work with your Windows setups? Mine is pretty bizarre.

**Comment by ebidel** [comment]
Very cool. Thanks for the quick fix on this one!

File: lib/Launcher.js [hunk 1]
```diff
@@ -142,20 +142,12 @@ class Launcher {
...
-          // Terminate chrome gracefully.
-          if (process.platform === 'win32')
-            childProcess.execSync(`taskkill /pid ${chromeProcess.pid}`);
-          else
-            process.kill(-chromeProcess.pid, 'SIGTERM');
-        }
+      if (chromeProcess.pid && temporaryUserDataDir) {
+        // Force kill chrome.
+        if (process.platform === 'win32')
+          childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T /F`);
```
Comment (aslushnikov) [inline lib/Launcher.js]: this is racing with protocol's browser.close. What happens if browser has already been closed? Could it be that we might terminate something else (in case this pid got reused)?

Comment (JoelEinbinder) [reply lib/Launcher.js]: Outdated, I check !chromeProcess.killed && chromeProcess.connected

**Comment by vsemozhetbyt** [comment]
1. This seems to fix https://github.com/GoogleChrome/puppeteer/issues/918, but Ctrl+C seems not to work:

```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: true,
      userDataDir: 'test-profile-dir',
    });
    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```

If I type Ctrl+C once, nothing happens. If I type Ctrl+C second time, node exits, but Chromium remains.

**Comment by vsemozhetbyt** [comment]
2. This DOES NOT fix https://github.com/GoogleChrome/puppeteer/issues/921: headless Chromium still does not preserve authorization (does not send cookies?).

**Comment by fhmd4k** [comment]
to fix #918:  in the `lib/Launcher.js` find this spawn chrome line:

`const chromeProcess = childProcess.spawn(chromeExecutable, chromeArguments, { detached: false });`
set `detached: false`

**Comment by fhmd4k** [comment]
#921:
In the headless mode, chromium can't save storage and cookie. But in the normal mode, it can.
I think it's chromium bug.

You can test it without puppeteer. Run chromium with the specified arguments`chromiumPath --user-data-dir=path --headless -- "https://www.google.com"`

**Comment by JoelEinbinder** [comment]
It appears to be working with localStorage but not with cookies. I'll look into it further.

File: lib/Launcher.js (hunk 1 above)
Comment (aslushnikov) [reply lib/Launcher.js]: This does reduce probability but doesn't fix the race.

File: lib/Launcher.js [hunk 2]
```diff
@@ -142,20 +142,12 @@ class Launcher {
...
-          // Terminate chrome gracefully.
-          if (process.platform === 'win32')
-            childProcess.execSync(`taskkill /pid ${chromeProcess.pid}`);
-          else
-            process.kill(-chromeProcess.pid, 'SIGTERM');
-        }
+      if (chromeProcess.pid && temporaryUserDataDir && !chromeProcess.killed && chromeProcess.connected) {
+        // Force kill chrome.
+        if (process.platform === 'win32')
+          childProcess.execSync(`taskkill /pid ${chromeProcess.pid} /T /F`);
```
Comment (aslushnikov) [inline lib/Launcher.js]: For the record: this still is racy

**Comment by sukrosono** [comment]
I will wait this one, can we expect [Browser.close](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-close) to return boolean? Currently i check it just return empty object.

File: lib/Launcher.js (hunk 2 above)
Comment (JoelEinbinder) [reply lib/Launcher.js]: Should be not racy anymore.

**Comment by JoelEinbinder** [comment]
@brutalcrozt Browser.close tries to close the browser, but it doesn't make any guarantees about when or if that will happen.

File: lib/Launcher.js [hunk 3]
```diff
@@ -126,12 +126,13 @@ class Launcher {
...
-
+    /** @type {?Connection} */
+    let connection = null;
     try {
       const connectionDelay = options.slowMo || 0;
       const browserWSEndpoint = await waitForWSEndpoint(chromeProcess, options.timeout || 30 * 1000);
-      const connection = await Connection.create(browserWSEndpoint, connectionDelay);
-      return new Browser(connection, options, killChrome);
+      connection = await Connection.create(browserWSEndpoint, connectionDelay);
+      return new Browser(connection, options, killChrome.bind(null, connection));
```
Comment (aslushnikov) [inline lib/Launcher.js]: no need to bind - you don't use it.

File: docs/api.md [hunk 4]
```diff
@@ -264,6 +265,10 @@ puppeteer.launch().then(async browser => {
 
 Closes browser with all the pages (if any were opened). The browser object itself is considered to be disposed and can not be used anymore.
 
+#### browser.disconnect()
+
+Disconnects Puppeteer from the browser, but leaves the Chromium process running.
```
Comment (aslushnikov) [inline docs/api.md]: ... This is needed to free up resources allocated for browser connection.

(and also a small example of puppeteer.connect + browser.disconnect)

File: test/test.js [hunk 5]
```diff
@@ -170,14 +163,28 @@ describe('Puppeteer', function() {
     }));
   });
   describe('Puppeteer.connect', function() {
-    it('should work', SX(async function() {
+    fit('should be able to connect multiple times to the same browser', SX(async function() {
```
Comment (aslushnikov) [inline test/test.js]: `s/fit/it/`

**Review by aslushnikov — APPROVED** [review]

**Comment by sukrosono** [comment]
I subscribe to this PR, i was thinking that i will get notified when it got merged. But it wasn't :confused:

**Comment by ronalb** [comment]
ok I'll subscribe also
