### PR TITLE
fix: ng-schematics install Windows

### LINKED ISSUE #11433: [Bug]: `ng e2e` with puppeteer fails out of the box
### Minimal, reproducible example

```TypeScript
> ng new test
# ...
> cd test
> ng e2e
# select puppeteer & jasmine
> ng e2e

Building tests 🛠️ ...

Error: spawn ./node_modules/.bin/tsc ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn ./node_modules/.bin/tsc',
  path: './node_modules/.bin/tsc',
  spawnargs: [ '-p', 'e2e/tsconfig.json' ]
}

 🛑 Test failed! 🛑
Please look at the output above to determine the issue!
```

### Error string

Error: spawn ./node_modules/.bin/tsc ENOENT

### Expectation

No error. Schematic should configure the `ng e2e` successfully.

### Reality

`ng e2e` fails with the above mentioned error on a completely fresh angular project (angular-cli v17.0.3).

### Puppeteer version

21.5.2

### Node version

18.18.2

### Package manager

npm

### Package manager version

9.8.1

### Operating system

Windows

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Closes #11433

### CODE REVIEW

File: packages/ng-schematics/src/builders/puppeteer/index.ts [hunk 1]
```diff
@@ -84,12 +85,13 @@ async function executeCommand(context: BuilderContext, command: string[]) {
...
     let path = context.workspaceRoot;
     if (context.target) {
-      path = `${path}/${project['root']}`;
+      path = join(path, (project['root'] as string | undefined) ?? '');
     }
 
     const child = spawn(executable, args, {
       cwd: path,
       stdio: 'inherit',
+      shell: true,
```
Comment (OrKoN) [inline packages/ng-schematics/src/builders/puppeteer/index.ts:94]: does win support shell = true? I recall there was some incompatibility there

**Review by OrKoN — APPROVED** [review]

File: packages/ng-schematics/src/builders/puppeteer/index.ts (hunk 1 above)
Comment (Lightning00Blade) [reply packages/ng-schematics/src/builders/puppeteer/index.ts:94]: So it seem its required for Windows else you get ENOENT error, even with fixed path
