### PR TITLE
fix: robustly check for launch executable

### LINKED ISSUE #8466: [Bug]: Crash with a specified browser channel
### Bug description

Steps to reproduce the problem:

1. Launch Puppeteer with a custom browser channel:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({channel: "chrome-dev"});
})();
```

# Expected
Browser is launched.

# Actual
Puppeteer crashes.

### Puppeteer version

14.2.1

### Node.js version

v18.0.0

### npm version

8.6.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
.../node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: `executablePath` must not be specified when `channel` is given.
    at assert (.../node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at ChromeLauncher.launch (.../node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:97:36)
    at async /Users/sadym/work/del_me/example.js:4:19

Node.js v18.0
```

### PR DESCRIPTION
**Pull request by jrandolf-google**
Fixes: #8466

### CODE REVIEW

File: src/node/Launcher.ts [hunk 1]
```diff
@@ -133,26 +133,9 @@ class ChromeLauncher implements ProductLauncher {
 
     isTempUserDataDir = false;
 
-    let chromeExecutable = executablePath;
-
-    if (channel) {
-      // executablePath is detected by channel, so it should not be specified by user.
-      assert(
-        typeof executablePath === 'string',
```
Comment (OrKoN) [inline src/node/Launcher.ts:141]: I think we should keep the error message? to hint users we they specify both options by mistake

**Review by OrKoN — APPROVED** [review]
