### PR TITLE
chore: Fix installing from GitHub URL

### LINKED ISSUE #5660: Cannot install v3.0.0-post from GitHub URL
* Puppeteer version: v3.0.0-post
* Platform / OS version: Windows 10 x64
* URLs (if applicable):
* Node.js version: v14.0.0-v8-canary20200407ca0d7f295b

```
j:\temp>npm install -g https://github.com/GoogleChrome/puppeteer
(node:3008) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
(node:1764) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.

> puppeteer@3.0.0-post install C:\Users\vmb\AppData\Roaming\npm\node_modules\puppeteer
> node install.js

Compiling TypeScript before install...
Error running TypeScript Error: Command failed: npm run tsc
(node:1288) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
(node:1144) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
'tsc' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.0.0-post tsc: `tsc --version && tsc -p . && cp src/protocol.d.ts lib/ && cp src/externs.d.ts lib/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@3.0.0-post tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vmb\AppData\Roaming\npm-cache\_logs\2020-04-16T14_48_13_944Z-debug.log

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:651:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm run tsc',
  stdout: '\n' +
    '> puppeteer@3.0.0-post tsc C:\\Users\\vmb\\AppData\\Roaming\\npm\\node_modules\\puppeteer\n' +
    '> tsc --version && tsc -p . && cp src/protocol.d.ts lib/ && cp src/externs.d.ts lib/\n' +
    '\n',
  stderr: '(node:1288) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.\n' +
    '(node:1144) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.\n' +
    "'tsc' is not recognized as an internal or external command,\r\n" +
    'operable program or batch file.\r\n' +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! errno 1\n' +
    'npm ERR! puppeteer@3.0.0-post tsc: `tsc --version && tsc -p . && cp src/protocol.d.ts lib/ && cp src/externs.d.ts lib/`\n' +
    'npm ERR! Exit status 1\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the puppeteer@3.0.0-post tsc script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\vmb\\AppData\\Roaming\\npm-cache\\_logs\\2020-04-16T14_48_13_944Z-debug.log\n'
}
npm WARN You are using a pre-release version of node and things may not work as expected

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@3.0.0-post install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@3.0.0-post install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vmb\AppData\Roaming\npm-cache\_logs\2020-04-16T14_48_14_217Z-debug.log
```

### PR DESCRIPTION
**Pull request by jackfranklin**
The change to the install script to require TypeScript works fine when
installing from npm (because on npm the `lib` directory with the
compiled code already exists) but doesn't if you install from a GitHub
URL. By default it seems npm uses the `files` list when you install from
GitHub which means it's missing a bunch of files that we need to
compile.

Additionally by default when installing from a GitHub URL npm doesn't
install the dependencies which is an issue for us when we need to
compile TypeScript.

The fix is to create a `prepare` script that runs TypeScript if
required. From the npm docs [1]:

> `prepare`: Run both BEFORE the package is packed and published, on
> local npm install without any arguments, and when installing git
> dependencies

And from the npm docs on install [2], it confirms that if a package has
a `prepare` script it is run when installing from GitHub:

> As with regular git dependencies, dependencies and devDependencies
> will be installed if the package has a prepare script, before the
> package is done installing.

Despite having the `prepare` script we still need the TypeScript check
in `install.js` to satisfy the 3rd scenario below where we need to force
a compile:

* If I'm a user installing `puppeteer@X` from npm, the module is
published with the `lib/` directory of compiled code, so I'm set.
* If I'm a user installing Puppeteer from GitHub, the `prepare` script
will run TypeScript for me so I'm set.
* If I'm a developer working on Puppeteer, the `prepare` script also
runs but _after_ `npm install` which means `install.js` fails as it
requires `./lib/helper.js`. So in `install.js` we call
`compileTypeScriptIfRequired` to catch this case.

Fixes #5660.

[1]: https://docs.npmjs.com/misc/scripts
[2]: https://docs.npmjs.com/cli/install

### CODE REVIEW

**Comment by jackfranklin** [comment]
Installing from this branch works for me:

```
npm i --save-dev https://github.com/GoogleChrome/puppeteer#fix-install-from-gh

> puppeteer@3.0.0-post install /Users/jacktfranklin/src/temp/test-pup/node_modules/puppeteer
> node install.js

Downloading Chromium r737027 - 118.4 Mb [====================] 100% 0.0s
Chromium (737027) downloaded to /Users/jacktfranklin/src/temp/test-pup/node_modules/puppeteer/.local-chromium/mac-737027
npm WARN test-pup@1.0.0 No description
npm WARN test-pup@1.0.0 No repository field.

+ puppeteer@3.0.0-post
added 49 packages from 77 contributors and audited 80 packages in 58.06s
```

File: typescript-if-required.js [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+  console.log('Puppeteer:', 'Compiling TypeScript...');
+  await compileTypeScript();
+}
+
+// It's being run as node typescript-if-required.js, not require('..')
+if (require.main === module)
+  compileTypeScriptIfRequired();
+
+
```
Comment (mathiasbynens) [inline typescript-if-required.js]:
```suggestion
```

**Review by mathiasbynens — APPROVED** [review]
