### PR TITLE
chore: run unit tests on node 10.15 + fix fs.promises access

### LINKED ISSUE #6548: Compatible issue with node@10.13 - node@10.17
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `5.4.0`
* Platform / OS version: `macOS 10.15.17
* URLs (if applicable):
* Node.js version: `10.15.0`

`fs.promises` is experimental in `node@10.13 ~ node@10.17`, so the result of `Object.getOwnPropertyDescriptor(require('fs'), 'promises').enumerable` is `false`, which means https://github.com/puppeteer/puppeteer/blob/main/src/common/helper.ts#L322 this line would throw `Can not read property open from undefined`

### PR DESCRIPTION
**Pull request by jackfranklin**
We saw in https://github.com/puppeteer/puppeteer/issues/6548 that the
`fs.promises` module was experimental in Node <10.17 and as such we
introduced issues for users on 10.15.

Until we can drop Node v10 (it's EOL is 30-04-20201
https://github.com/nodejs/Release#release-schedule) we should run our
tests on an old Node 10 to avoid regressing in this area.

Closes #6548 .

### CODE REVIEW

**Comment by jackfranklin** [comment]
Note that I'm expecting the 10.15 CI run to fail, but hoping that I can then patch https://github.com/puppeteer/puppeteer/pull/6549 in and that will fix it.

**Review by mathiasbynens — APPROVED** [review]

**Comment by jackfranklin** [comment]
@mathiasbynens PTAL at the latest commit. I took the work in #6549 but extracted it into a helper function that we can use in the mean time. That, plus running tests on Node 10.15, should ensure we don't hit this again.

File: src/common/helper.ts [hunk 1]
```diff
@@ -344,6 +344,31 @@ async function readProtocolStream(
...
+async function importFSModule(): Promise<typeof import('fs')> {
+  if (!isNode) {
+    throw new Error('Cannot load the fs module API outside of Node.');
+  }
+
+  const fs = await import('fs');
+  if (fs.promises) {
+    return fs;
+  } else {
+    return fs.default;
```
Comment (mathiasbynens) [inline src/common/helper.ts]: nit: no else after return (we should probably enable the eslint rule for it)

**Review by mathiasbynens — APPROVED** [review]
