### PR TITLE
fix: content() not showing comments outside html tag

### LINKED ISSUE #10291: [Bug]: Page.content() ignores some HTML comments
### Bug expectation

The `Page.content()` function should return the full HTML content. ([Docs](https://pptr.dev/api/puppeteer.page.content/))
In my case, all comments outside if the `html` tag disappear.

Example page:
```html
<!DOCTYPE html>
<!-- this comment before the html tag -->
<html lang="en">
<!-- this comment is in the html -->
<head>
   <!-- this comment is in the head -->
  <meta charset="UTF-8">
  <title>TEST</title>
</head>
<body>
    <h1>TEST</h1>
    <!-- this comment is in the body -->
</body>
</html>
<!-- I am a comment after the html tag -->
```

In the response of `page.content()` the comments `<!-- I am a comment after the html tag -->` and `<!-- this comment before the html tag -->` are missing.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import puppeteer from 'puppeteer'; // TS/ESM are all supported.

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://constantin-graf-temp.s3.fr-par.scw.cloud/test.html', {
    waitUntil: 'load'
  });
  let content = await page.content();
  console.log(content);
  await browser.close();
})();
```

### Error string

no error

### Puppeteer configuration

_No response_

### Puppeteer version

20.5.0

### Node version

20.2.0

### Package manager

npm

### Package manager version

9.6.6

### Operating system

Linux

### PR DESCRIPTION
**Pull request by Lightning00Blade**
Sadly we can't just use `new XMLSerializer().serializeToString(document)` as that creates an attribute on the `html` tag -> `xmlns="http://www.w3.org/1999/xhtml"`

Closes #10291

### CODE REVIEW

File: packages/puppeteer-core/src/common/bidi/BrowsingContext.ts [hunk 1]
```diff
@@ -240,34 +240,39 @@ export class BrowsingContext extends EventEmitter {
...
     ]);
   }
 
   async content(): Promise<string> {
     return await this.evaluate(() => {
-      let retVal = '';
-      if (document.doctype) {
-        retVal = new XMLSerializer().serializeToString(document.doctype);
+      let content = '';
+      for (const node of document.childNodes) {
```
Comment (OrKoN) [inline packages/puppeteer-core/src/common/bidi/BrowsingContext.ts]: can we deduplicate this or not yet?

**Review by OrKoN — APPROVED** [review]

File: packages/puppeteer-core/src/common/bidi/BrowsingContext.ts (hunk 1 above)
Comment (Lightning00Blade) [reply packages/puppeteer-core/src/common/bidi/BrowsingContext.ts]: We can extract it as it the same way we did for `setContent`.

Comment (OrKoN) [reply packages/puppeteer-core/src/common/bidi/BrowsingContext.ts]: let's do that!

File: packages/puppeteer-core/src/common/util.ts [hunk 2]
```diff
@@ -510,7 +510,7 @@ export async function waitWithTimeout<T>(
     timeout,
   });
 
-  return await Deferred.race([promise, deferred.valueOrThrow()]).finally(() => {
+  return await Deferred.race([promise, deferred]).finally(() => {
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/common/util.ts:513]: This was causing timeouts in test for BiDi, and they happened on a hook, stopped like 4 test from running.
Created an EsLint rule to prevent this for the feature.

File: .eslintrc.js [hunk 3]
```diff
@@ -200,6 +200,12 @@ module.exports = {
             selector:
               'MemberExpression[object.name="Promise"][property.name="race"]',
           },
+          {
+            message:
+              'Deferred `valueOrThrow` should not be called in `Deferred.race()` pass deferred directly',
+            selector:
+              'CallExpression[callee.object.name="Deferred"][callee.property.name="race"] MemberExpression[property.name="valueOrThrow"]',
```
Comment (Lightning00Blade) [inline .eslintrc.js]:
```suggestion
              'CallExpression[callee.object.name="Deferred"][callee.property.name="race"] > ArrayExpression > CallExpression[callee.property.name="valueOrThrow"]',
```

**Review by OrKoN — APPROVED** [review]
