### PR TITLE
fix: do not pass --{enable,disable}-features twice when user-provided

### LINKED ISSUE #11208: [Bug] Merging disabled and enabled features does not remove additional enable/disable args
Inspect arguments for the browser for the following snippet:

```
const puppeteer = require("puppeteer");

(async () => {
  await puppeteer.launch({
    headless: "new",
    args: ["--disable-features=Test"]
  });
})();
```

You will see:
```
.cache/puppeteer/chrome/mac_arm-118.0.5993.70/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing --allow-pre-commit-input --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=Translate,AcceptCHFrame,MediaRouter,OptimizationHints,ProcessPerSiteUpToMainFrameThreshold,Test --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-search-engine-choice-screen --disable-sync --enable-automation --enable-blink-features=IdleDetection --enable-features=NetworkServiceInProcess2 --export-tagged-pdf --force-color-profile=srgb --metrics-recording-only --no-first-run --password-store=basic --use-mock-keychain --headless=new --hide-scrollbars --mute-audio about:blank --disable-features=Test --remote-debugging-port=0
``` 

Although the Test feature is merged into the first flag it's not removed as the separate argument which might be confusing and might break if the browser changes the order of parsing. We probably should remove the merged args.

### PR DESCRIPTION
**Pull request by thiagowfx**
Currently, whenever the user provides:

    args: '--disable-features=TestDisableFeatures'

The --disable-features flag appears twice in chrome arguments.

Make it appear only once, by merging them.

Ditto for --enable-features.

Fixed: #11208

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

File: packages/puppeteer-core/src/node/ChromeLauncher.ts [hunk 1]
```diff
@@ -166,6 +166,14 @@ export class ChromeLauncher extends ProductLauncher {
   override defaultArgs(options: BrowserLaunchArgumentOptions = {}): string[] {
     // See https://github.com/GoogleChrome/chrome-launcher/blob/main/docs/chrome-flags-for-tools.md
 
+    const userDisabledFeatures = getFeatures(
+      '--disable-features',
+      options.args
+    );
+    if (userDisabledFeatures.length > 0) {
+      removeMatching(options.args ?? [], /^--disable-features=.*/);
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/node/ChromeLauncher.ts]: Nit: 
```suggestion
    if (options.args && userDisabledFeatures.length > 0) {
      removeMatching(options.args, /^--disable-features=.*/);
```

File: packages/puppeteer-core/src/node/ChromeLauncher.ts [hunk 2]
```diff
@@ -297,3 +310,21 @@ export function getFeatures(flag: string, options: string[] = []): string[] {
...
     }) as string[];
 }
+
+/**
+ * Removes all elements in-place from the given array that match the given
+ * regular expression.
+ *
+ * @internal
+ */
+export function removeMatching(array: string[], regex: RegExp): string[] {
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/node/ChromeLauncher.ts]: Can we create the reg-ex in this function it would be nice to have a consistent API for extracting and removing. 
Than we a better name would be `removeMatchingFlags`.

**Review by Lightning00Blade — APPROVED** [review]

File: packages/puppeteer-core/src/node/ChromeLauncher.ts (hunk 2 above)
Comment (thiagowfx) [reply packages/puppeteer-core/src/node/ChromeLauncher.ts]: Do you mean to change this to `string`? OK

Comment (thiagowfx) [reply packages/puppeteer-core/src/node/ChromeLauncher.ts]: Done
