### PR TITLE
fix(Navigation): correctly wait for navigation in Page.goto

### LINKED ISSUE #1218: `page.goto` is littered with races
Since the migration to lifecycle events (ce8a952044ef318baf3d9ff25157e41571293de5), the `page.goto`, `page.waitForNavigation` and other navigation methods are terribly flaky.

We're fighting it upstream. This should be fixed before releasing next PPTR version.

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch:
- starts persisting lifecycle state for every frame
- migrates NavigationWatcher to rely on the frame's lifecycle state
- refactors Page.goto to properly return navigation errors

Fixes #1218.

### CODE REVIEW

File: lib/NavigatorWatcher.js [hunk 1]
```diff
@@ -15,66 +15,85 @@
...
   }
 
   /**
    * @return {!Promise<?Error>}
    */
-  async waitForNavigation() {
-    this._eventListeners = [];
+  _timeoutPromise() {
+    if (!this._timeout)
+      return new Promise(() => {});
```
Comment (JoelEinbinder) [inline lib/NavigatorWatcher.js]: null

File: lib/NavigatorWatcher.js [hunk 2]
```diff
@@ -15,66 +15,85 @@
...
-    if (this._timeout) {
-      const watchdog = new Promise(fulfill => this._maximumTimer = setTimeout(fulfill, this._timeout))
-          .then(() => 'Navigation Timeout Exceeded: ' + this._timeout + 'ms exceeded');
-      navigationPromises.push(watchdog);
-    }
+  /**
+   * @return {!Promise<?Error>}
+   */
+  async waitForNavigation() {
+    this._eventListeners = [
```
Comment (JoelEinbinder) [inline lib/NavigatorWatcher.js]: constructor!

File: lib/NavigatorWatcher.js [hunk 3]
```diff
@@ -15,66 +15,85 @@
...
+    if (!checkLifecycle(this._frame, this._waitUntil))
       return;
-    this._pendingEvents.delete(pptrName);
-    if (this._pendingEvents.size === 0)
-      this._pendingEventsCallback();
+    this._lifecycleCompleteCallback();
+
+    /**
+     * @param {!Frame} frame
+     * @param {!Array<string>} waitUntil
```
Comment (JoelEinbinder) [inline lib/NavigatorWatcher.js]: @return {boolean}

File: lib/NavigatorWatcher.js [hunk 4]
```diff
@@ -15,66 +15,85 @@
...
+     */
+    function checkLifecycle(frame, waitUntil) {
+      let result = true;
+      for (let i = 0; result && i < waitUntil.length; ++i)
```
Comment (JoelEinbinder) [inline lib/NavigatorWatcher.js]: for (var event of waitUntil) {
if (!frame._lifecycleEvents.has(event)) return false;
}

File: lib/Page.js [hunk 5]
```diff
@@ -453,30 +453,44 @@ class Page extends EventEmitter {
...
-    if (unreachableURL) {
-      const request = requests.get(unreachableURL) || null;
-      const failure = request ? request.failure() : null;
-      throw new Error('Failed to navigate: ' + url + (failure ? ' ' + failure.errorText : ''));
-    }
     const request = requests.get(this.mainFrame().url());
     return request ? request.response() : null;
+
+    /**
+     *
```
Comment (JoelEinbinder) [inline lib/Page.js]: remove

**Review by JoelEinbinder — APPROVED** [review]

File: lib/NavigatorWatcher.js (hunk 1 above)
Comment (aslushnikov) [reply lib/NavigatorWatcher.js]: Done.

File: lib/NavigatorWatcher.js (hunk 2 above)
Comment (aslushnikov) [reply lib/NavigatorWatcher.js]: done

File: lib/NavigatorWatcher.js (hunk 4 above)
Comment (aslushnikov) [reply lib/NavigatorWatcher.js]: This is nice, done!

File: lib/NavigatorWatcher.js (hunk 3 above)
Comment (aslushnikov) [reply lib/NavigatorWatcher.js]: Done

File: lib/Page.js (hunk 5 above)
Comment (aslushnikov) [reply lib/Page.js]: done
