### PR TITLE
fix: custom sessions should not emit targetcreated events

### LINKED ISSUE #8787: [Bug]: `browserContext.on('targetcreated', t => t.createCDPSession())` goes haywire
### Bug description

Steps to reproduce the problem:

```js
const browser = await puppeteer.launch();
browser.browserContexts()[0].on('targetcreated', async target => {
	console.log(target.url());
	const cdp = await target.createCDPSession();
	// (do something with cdp)
});
await browser.newPage();
```
This prints 'about:blank' over and over.

Apparently `Target#createCDPSession` causes `targetcreated` to be fired again.
This is most likely caused by #8520 (so v16.0.0). The snippet worked correctly in v15.3.2.

### Puppeteer version

16.1.0

### Node.js version

18.7.0

### npm version

8.15.1

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
about:blank
about:blank
about:blank
about:blank
about:blank
...
```

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #8787

### CODE REVIEW

File: src/common/Browser.ts [hunk 1]
```diff
@@ -492,8 +492,8 @@ export class Browser extends EventEmitter {
       session,
       context,
       this.#targetManager,
-      () => {
-        return this.#connection.createSession(targetInfo);
+      (emulateAutoAttach: boolean) => {
```
Comment (jrandolf) [inline src/common/Browser.ts]: Use `isAutoAttachEmulated`

File: src/common/Connection.ts [hunk 2]
```diff
@@ -229,23 +229,38 @@ export class Connection extends EventEmitter {
...
   /**
-   * @param targetInfo - The target info
-   * @returns The CDP session that is created
+   * @internal
    */
-  async createSession(
-    targetInfo: Protocol.Target.TargetInfo
+  async _createSession(
+    targetInfo: Protocol.Target.TargetInfo,
+    emulateAutoAttach = true
```
Comment (jrandolf) [inline src/common/Connection.ts]: Ditto

**Review by jrandolf-google — APPROVED** [review]
