### PR TITLE
test: implement workarounds for current state of WebDriver BiDi

### LINKED ISSUE #11913: Fix tests disabled after refactoring
With the following tests have been disabled: https://github.com/puppeteer/puppeteer/pull/11836

We need to investigate the issues and recover test coverage:

[navigation.spec] navigation Page.goto should fail when navigating to bad SSL
  https://github.com/w3c/webdriver-bidi/issues/657

[frame.spec] Frame specs Frame Management should detach child frames on navigation
  https://github.com/w3c/webdriver-bidi/issues/659

[frame.spec] Frame specs Frame Management should send \"framenavigated\" when navigating on anchor URLs
  https://github.com/w3c/webdriver-bidi/issues/657

[frame.spec] Frame specs Frame Management should support framesets
  https://github.com/w3c/webdriver-bidi/issues/659

[navigation.spec] navigation Page.goBack should work with HistoryAPI
  browsingContext.navigationStarted event not emitted for fragment navigation

[navigation.spec] navigation Page.goto should fail when main resources failed to load
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when navigating and show the url at the error message
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when navigating to bad SSL after redirects
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should fail when server returns 204
  https://github.com/w3c/webdriver-bidi/issues/657

[navigation.spec] navigation Page.goto should work with anchor navigation
  browsingContext.navigationStarted event not emitted for fragment navigation

[navigation.spec] navigation Page.waitForNavigation should work with DOM history.back()/history.forward()
  browsingContext.navigationStarted event not emitted for fragment navigatio

[navigation.spec] navigation Page.waitForNavigation should work with history.pushState()
  browsingContext.navigationStarted event not emitted for fragment navigation

[network.spec] network Response.fromCache should work

[oopif.spec] OOPIF should support frames within OOP iframes
  Fetch error

[oopif.spec] OOPIF should support lazy OOP frames
  https://bugzilla.mozilla.org/show_bug.cgi?id=187816

[oopif.spec] OOPIF should wait for inner OOPIFs
  Fetch error

### PR DESCRIPTION
**Pull request by OrKoN**
- [x] [navigation.spec] navigation Page.goto should fail when navigating to bad SSL
- [x] [frame.spec] Frame specs Frame Management should detach child frames on navigation
- [x] [frame.spec] Frame specs Frame Management should send \"framenavigated\" when navigating on anchor URLs
- [x] [frame.spec] Frame specs Frame Management should support framesets
- [x] [navigation.spec] navigation Page.goBack should work with HistoryAPI
- [x] [navigation.spec] navigation Page.goto should fail when main resources failed to load
- [x] [navigation.spec] navigation Page.goto should fail when navigating and show the url at the error message
- [x] [navigation.spec] navigation Page.goto should fail when navigating to bad SSL after redirects
- [x] [navigation.spec] navigation Page.goto should fail when server returns 204
- [x] [navigation.spec] navigation Page.goto should work with anchor navigation
- [x] [navigation.spec] navigation Page.waitForNavigation should work with DOM history.back()/history.forward()
- [x] [navigation.spec] navigation Page.waitForNavigation should work with history.pushState()
- [ ] [network.spec] network Response.fromCache should work (was failing previously)
- [x] [oopif.spec] OOPIF should support frames within OOP iframes
- [ ] [oopif.spec] OOPIF should support lazy OOP frames (not supported yet in Firefox)
- [ ] [oopif.spec] OOPIF should wait for inner OOPIFs (uses Chrome-specific features)
- [ ] [navigation.spec] navigation Page.goto should work when page calls history API in beforeunload 

Closes https://github.com/puppeteer/puppeteer/issues/11913

### CODE REVIEW

File: packages/puppeteer-core/src/bidi/core/Session.ts [hunk 1]
```diff
@@ -105,6 +105,19 @@ export class Session
     browserEmitter.once('closed', ({reason}) => {
       this.dispose(reason);
     });
+
+    // TODO: Currently, some implementations do not emit navigationStarted event
+    // for fragement navigations (as per spec) and some do. This could emits a
```
Comment (OrKoN) [inline packages/puppeteer-core/src/bidi/core/Session.ts]:
```suggestion
    // for fragement navigations (as per spec) and some do. This code emits a
```

File: packages/puppeteer-core/src/bidi/core/Session.ts [hunk 2]
```diff
@@ -105,6 +105,19 @@ export class Session
     browserEmitter.once('closed', ({reason}) => {
       this.dispose(reason);
     });
+
+    // TODO: Currently, some implementations do not emit navigationStarted event
+    // for fragement navigations (as per spec) and some do. This code emits a
```
Comment (OrKoN) [inline packages/puppeteer-core/src/bidi/core/Session.ts]:
```suggestion
    // for fragment navigations (as per spec) and some do. This code emits a
```

File: test/TestExpectations.json [hunk 3]
```diff
@@ -3233,6 +3238,13 @@
     "parameters": ["cdp", "firefox"],
     "expectations": ["FAIL"]
   },
+  {
+    "testIdPattern": "[navigation.spec] navigation Page.goto should work when page calls history API in beforeunload",
+    "platforms": ["darwin", "linux", "win32"],
+    "parameters": ["firefox", "webDriverBiDi"],
+    "expectations": ["FAIL"],
+    "comment": "History navigation is breaking the Puppeteer expecation about navigation."
```
Comment (OrKoN) [inline test/TestExpectations.json:3238]:
```suggestion
    "comment": "History navigation is breaking the Puppeteer expectation about navigation events order."
```

File: packages/puppeteer-core/src/bidi/core/Session.ts (hunk 1 above)
Comment (jrandolf) [inline packages/puppeteer-core/src/bidi/core/Session.ts]:
```suggestion
    // for fragment navigations (as per spec) and some do. This could emits a
```

File: packages/puppeteer-core/src/bidi/core/Session.ts [hunk 4]
```diff
@@ -105,6 +105,19 @@ export class Session
     browserEmitter.once('closed', ({reason}) => {
       this.dispose(reason);
     });
+
+    // TODO: Currently, some implementations do not emit navigationStarted event
+    // for fragement navigations (as per spec) and some do. This could emits a
+    // synthetic navigationStarted to work around this inconsistency.
+    const seen = new WeakSet();
+    this.on('browsingContext.fragmentNavigated', info => {
```
Comment (jrandolf) [inline packages/puppeteer-core/src/bidi/core/Session.ts:113]: Could we do this only for firefox? We can add a check detecting firefox from the session's info.

**Review by jrandolf-google — APPROVED** [review]
lgtm % comments

File: packages/puppeteer-core/src/bidi/core/Session.ts (hunk 4 above)
Comment (OrKoN) [reply packages/puppeteer-core/src/bidi/core/Session.ts:113]: We could but 1) it does not affect Chrome because it already handles duplicate events 2) we will fix Chrome to behave similarly as Firefox so it would allow us to roll changes more easily.
