### PR TITLE
fix(Page): support anchor navigation

### LINKED ISSUE #257: Hash-only navigation doesn't work
Since the hash-only navigation doesn't cause any network requests and doesn't cause load event, 
the following gets stuck:

```js
const puppeteer = require('puppeteer');
(async() => {
  let browser = await puppeteer.launch();
  let page = await browser.newPage();
  await page.goto('https://example.com');
  await page.goto('https://example.com#ohh'); // <== stuck here
  browser.close();
})();

```

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch fixes puppeteer navigation primitives to work with
same-document navigation.

In browser world, same-document navigation happens when document's URL is changed,
but document instance is not re-created. Some common scenarios
for same-document navigation are:
- History API
- anchor navigation

With this patch:
- pptr starts dispatching `framenavigated` event when frame's URL gets
changed due to same-document navigation
- `page.waitForNavigation` now works with same-document navigation
- `page.goBack()` and `page.goForward()` are handled correctly.

Fixes #257.

### CODE REVIEW

File: lib/NavigatorWatcher.js [hunk 1]
```diff
@@ -43,8 +43,10 @@ class NavigatorWatcher {
     this._frame = frame;
     this._initialLoaderId = frame._loaderId;
     this._timeout = timeout;
+    this._hasSameDocumentNavigation = false;
     this._eventListeners = [
       helper.addEventListener(this._frameManager, FrameManager.Events.LifecycleEvent, this._checkLifecycleComplete.bind(this)),
+      helper.addEventListener(this._frameManager, FrameManager.Events.FrameNavigatedWithinDocument, this._navigatedWithingDocument.bind(this)),
```
Comment (JoelEinbinder) [inline lib/NavigatorWatcher.js]: WithinDocument

**Review by JoelEinbinder — APPROVED** [review]

File: lib/NavigatorWatcher.js (hunk 1 above)
Comment (aslushnikov) [reply lib/NavigatorWatcher.js]: Done.
