### PR TITLE
fix: make exposeFunction work for frames

### LINKED ISSUE #690: Expose function doesn't add to frames the first time.
It looks like exposeFunction is only running in the mainframe until a reload happens.

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Fixes #690

### CODE REVIEW

File: lib/Page.js [hunk 1]
```diff
@@ -289,8 +289,9 @@ class Page extends EventEmitter {
     this._pageBindings[name] = puppeteerFunction;
 
     const expression = helper.evaluationString(addPageBinding, name);
-    await this._client.send('Page.addScriptToEvaluateOnNewDocument', { source: expression });
-    await this._client.send('Runtime.evaluate', { expression, returnByValue: true });
+    await this._client.send('Page.addScriptToEvaluateOnNewDocument', {source: expression});
+    for (const frame of this.frames())
+      await frame.evaluate(expression).catch(debugError);
```
Comment (aslushnikov) [inline lib/Page.js]: nit: Promise.all it?

**Review by aslushnikov — APPROVED** [review]

File: lib/Page.js (hunk 1 above)
Comment (JoelEinbinder) [reply lib/Page.js]: Done.

**Review by aslushnikov — APPROVED** [review]
Thanks!
