### PR TITLE
fix(evaluate): throw error when page reloads during page.evaluate.

### LINKED ISSUE #2021: page.evaluate unpredictable when it triggers a reload
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.0.0
* Platform / OS version: Mac OS 10.13.3
* URLs (if applicable): 
* Node.js version: 9.5.0

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

I'm aware that this is nonsense code 🙂 , this is just to replicate the unpredictable behavior of `.evaluate`. Following up on #2020.

1. execute
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  try {
    const page = await browser.newPage();
    await page.goto('https://www.google.com/');

    const result = await page.evaluate(function () {
      location.reload();
      return new Promise(resolve => {
        setTimeout(() => resolve({}), 0);
      });
    });

    console.log('result', result);
  } catch (err) {
    console.log('error', err.message);
  } finally {
    await browser.close();
  }
})();
```

**What is the expected result?**

it prints
```
error <Some error here>
```
or 
```
result {}
```

**What happens instead?**

it prints
```
result undefined
```

Which seems like it introduces a third state to the result of `.evaluate`. Strangely enough, when you change the object by a string or number it does print the value.

```js
const result = await page.evaluate(function () {
  location.reload();
  return new Promise(resolve => {
    setTimeout(() => resolve(1), 0);
  });
});
// result 1
```

Increasing the timeout on the promise results in an error 👍 

```js
const result = await page.evaluate(function () {
  location.reload();
  return new Promise(resolve => {
    setTimeout(() => resolve({}), 1000);
  });
});
// error Protocol error (Runtime.callFunctionOn): Execution context was destroyed. undefined
```

Unless you return a primitive

```js
const result = await page.evaluate(function () {
  location.reload();
  return new Promise(resolve => {
    setTimeout(() => resolve(1), 1000);
  });
});
// result 1
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #2021.

### CODE REVIEW

**Review by JoelEinbinder — APPROVED** [review]

File: test/test.js [hunk 1]
```diff
@@ -474,6 +484,15 @@ describe('Page', function() {
...
       expect(result).toBe(undefined);
     });
+    it('should fail for circular object', async({page, server}) => {
+      const result = await page.evaluate(() => {
+        const a = {};
+        const b = {a};
+        a.b = b;
+        return a;
+      });
+      expect(result).toBe(undefined);
```
Comment (Janpot) [inline test/test.js:494]: @aslushnikov Is there any reason on why this should return `undefined`? I think throwing an error would be more appropriate. Think of the consumer of this API. They will not realise their result is circular, or it might happen only in some occasions. Or maybe sometimes `undefined` is a legit output of their function. How will they be able to distinguish these cases from a bug? How will they be notified of bugs in their code?

Comment (aslushnikov) [reply test/test.js:494]: @Janpot the motivation behind this was to let people use `page.evaluate` safely without caring on the return value. Consider the following simple script:

```js
await page.evaluate(() => window.foo = window);
```

Technically, the `page.evaluate` should throw since the expression returns non-serializable value,
but most of the time its unintentional.

> How will they be able to distinguish these cases from a bug? How will they be notified of bugs in their code?

I filed https://github.com/GoogleChrome/puppeteer/issues/2079 with a solution that will hopefully address your concerns and satisfy our usecase.

Comment (Janpot) [reply test/test.js:494]: @aslushnikov How did you arrive at this conclusion: _but most of the time its unintentional._?
In my experience it's exactly the opposite, I've never had to evaluate and not care about the result.

Comment (aslushnikov) [reply test/test.js:494]: > How did you arrive at this conclusion: but most of the time its unintentional.?

@Janpot once we started throwing errors, we instantly had a bunch of feedback on both bugtracker and internally about the unwanted errors caused by one-liners in `page.evaluate`.

Comment (Janpot) [reply test/test.js:494]: Ok, I don't really agree with API design like this but I see you want to be sort of pragmatic, and I don't have arguments against that that would actually change your mind 🙂. I'll settle for
```js
async function evaluate (page, ...args) {
  const result = await page.evaluate(...args);
  if (result === puppeteer.UNSERIALIZABLE_VALUE) {
    throw new Error('Unserializable value');
  }
  retun result;
}
```
then.
