### PR TITLE
fix: always use ENV executable path when present

### LINKED ISSUE #7981: [Bug]: PUPPETEER_EXECUTABLE_PATH not respected on Linux/aarch64
### Bug description

On a arm64 platform and Debian 10, puppeteer `launch` does not respect the `PUPPETEER_EXECUTABLE_PATH` and does not use the default chromium location. More succinctly, when the platform is non-darwin arm64, the only way to specify a chromium executable path is to provide it via `LaunchOptions`. (see #5167)

Steps to reproduce the problem:

1. Environment setup:

```
FROM debian:buster-slim

RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash - \
  && apt-get update && apt-get install -y chromium nodejs npm

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

RUN npm install puppeteer
```

2. Launch puppeteer/chromium:

```shell
› docker build -t pup:bug -f Dockerfile.bug .
› docker run -it --rm pup:bug env | grep PUPPETEER
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
› docker run -it --rm pup:bug node -e "require('puppeteer').launch()"
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:221:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:221:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

3. What I expect to happen:

Puppeteer uses `/usr/bin/chromium` to launch since it is defined via `PUPPETEER_EXECUTABLE_PATH`.

4. What actually happens:

Launcher.js detects that the platform is arm64 and does not use `resolveExecutablePath`. `/usr/bin/chromium-browser` is assumed to exist and used as the executable path.

### Puppeteer version

Latest

### Node.js version

10+

### npm version

5.8

### What operating system are you seeing the problem on?

Linux, macOS

### Relevant log output

```shell
› docker build -t pup:bug -f Dockerfile.bug .
› docker run -it --rm pup:bug env | grep PUPPETEER
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
› docker run -it --rm pup:bug node -e "require('puppeteer').launch()"
(node:1) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:221:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
    at ChildProcess.helper_js_1.helper.addEventListener (/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:221:85)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by jbielick**
**What kind of change does this PR introduce?**

Fixes #7981 

These changes:

1. Allow the ENV variable to always be used when defined and not specified in LaunchOptions (and when not puppeteer-core)
2. Retain the existing behavior of assuming /usr/bin/chromium-browser on platforms like Ubuntu, Alpine (exact if-conditions preserved to avoid any breaking changes + an added check for file.exists?)
3. Add some tests for this particular portion of the code.

**Did you add tests for your changes?**

Yes

**If relevant, did you update the documentation?**

No. I could add a note about precedence if desired.

**Summary**

#7981

On linux/arm64, puppeteer always assumes /usr/bin/chromium-browser exists. It ignores `PUPPETEER_EXECUTABLE_PATH` and fails when /usr/bin/chromium-browser doesn't exist. Not all linux distros install to /usr/bin/chromium-browser, so it would be better to allow PUPPETEER_EXECUTABLE_PATH` to have precedence. Debian for instance installs to /usr/bin/chromium. I can't launch chromium unless I explicitly pass an executable path in `LaunchOptions`.

Some recent changes to allow arm64 environments (including M1 macs) to launch a chromium installation successfully before arm-compatible builds were downloadable prevented the usage of PUPPETEER_EXECUTABLE_PATH in some environments. Currently, when the platform is not darwin and the arch is arm64, an executable cannot be specified using the environment variable.

Generally speaking, environment variables have highest precedence for options such as this since they depend on system configuration.

**Does this PR introduce a breaking change?**

No. An executablePath provided via LaunchOptions always gets used. If empty, the ENV var is used. The assumed default executable of `/usr/bin/chromium-browser` **is retained** in case its being relied on (though, if PUPPETEER_EXECUTABLE_PATH is _also_ set, it would start working differently). The assumed scope of `if not darwin and arm64` was too broad, so this narrows it. `/usr/bin/chromium-browser` would be present if the OS was Ubuntu, but not Debian. I presume Ubuntu is more common so it was used.

### CODE REVIEW

File: src/node/Launcher.ts [hunk 1]
```diff
@@ -146,15 +146,9 @@ class ChromeLauncher implements ProductLauncher {
 
       chromeExecutable = executablePathForChannel(channel);
     } else if (!executablePath) {
-      // Use Intel x86 builds on Apple M1 until native macOS arm64
```
Comment (jbielick) [inline src/node/Launcher.ts:149]: I might have missed the point, but this comment seems outdated because `/usr/bin/chromium-browser` isn't always an x86 build and the comment does not match the condition `!== 'darwin'`

File: src/node/Launcher.ts [hunk 2]
```diff
@@ -813,22 +809,30 @@ function resolveExecutablePath(launcher: ChromeLauncher | FirefoxLauncher): {
         : undefined;
       return { executablePath, missingText };
     }
+    const ubuntuChromiumPath = '/usr/bin/chromium-browser';
+    if (
+      product === 'chrome' &&
+      os.platform() !== 'darwin' &&
```
Comment (jbielick) [inline src/node/Launcher.ts:815]: It was tempting to change this to `os.platform() === 'linux'` because `/usr/bin/chromium-browser` seemed ~~only applicable to Ubuntu from what I could tell~~ APK (alpine) also uses this location.

Comment (jbielick) [reply src/node/Launcher.ts:815]: ~~It didn't seem like `os.arch() === 'arm64'` should be retained anymore. Whether `chromium-browser` amd64 or arm64 build is installed it will be in the same location. Should it be retained so that it only behaves this way on arm64 systems because that's the way it used to behave? The current conditions here would add preference to a pre-installed `/usr/bin/chromium-browser` instead of downloading one on non-darwin platforms.~~

I've updated this to retain the `os.arch() === 'arm64'` so no breaking change would occur in which a pre-existing chromium installation would take automatic precedence over the normally downloaded chromium.

File: src/node/Launcher.ts (hunk 1 above)
Comment (OrKoN) [reply src/node/Launcher.ts:149]: It looks it was introduced in https://github.com/puppeteer/puppeteer/pull/7099

**Comment by jbielick** [comment]
Seeing the firefox test fail leads me to believe a couple of these tests should have `itChromeOnly` so they only run for chrome since the `product === 'chrome` is in the conditional for the asserted behavior. Updated pushed.

**Comment by OrKoN** [comment]
LGTM (requesting a second review from @jrandolf)

**Review by jrandolf-zz — APPROVED** [review]
SGTM

**Review by OrKoN — APPROVED** [review]

**Comment by jbielick** [comment]
Thank you, @OrKoN and @jrandolf
