### PR TITLE
fix: waitForSelector should work for pseudo classes

### LINKED ISSUE #6830: waitForSelector("…:focus") doesn’t resolve on focus change
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: NixOS
* URLs (if applicable):
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

```js
const puppeteer = require("puppeteer");

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.evaluate(() => {
    const e = document.createElement("input");
    document.body.append(e);
    setTimeout(() => e.focus(), 1000);
  });
  await page.waitForSelector("input:focus");
  await browser.close();
})();
```

**What is the expected result?**

`waitForSelector("input:focus")` should resolve when focus changes to the input element.

**What happens instead?**

`waitForSelector("input:focus")` hangs and times out. I think this is because it’s only listening to DOM mutations, which a focus change is not.

If I `await page.waitForSelector("input:focus", { visible: true })` instead, that resolves as expected.

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #6830

### CODE REVIEW

File: packages/puppeteer-core/src/api/Frame.ts [hunk 1]
```diff
@@ -720,13 +721,12 @@ export abstract class Frame extends EventEmitter<FrameEvents> {
...
+    const {updatedSelector, QueryHandler, selectorHasPseudoClasses} =
       getQueryHandlerAndSelector(selector);
-    return (await QueryHandler.waitFor(
-      this,
-      updatedSelector,
-      options
-    )) as ElementHandle<NodeFor<Selector>> | null;
+    return (await QueryHandler.waitFor(this, updatedSelector, {
+      ...options,
+      polling: selectorHasPseudoClasses ? PollingOptions.RAF : undefined,
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/api/Frame.ts]: We need change the order else the `polling` from the user is not respected.
Or we need instead of `undefined` -> `options.polling`
```suggestion
      polling: selectorHasPseudoClasses ? PollingOptions.RAF : undefined,
      ...options,
```
image

**Review by Lightning00Blade — APPROVED** [review]
LGTM with comment

File: packages/puppeteer-core/src/api/Frame.ts (hunk 1 above)
Comment (OrKoN) [reply packages/puppeteer-core/src/api/Frame.ts]: Wait but WaitForSelectorOptions does not allow polling?
