### PR TITLE
fix(page): intersect content quads with viewport

### LINKED ISSUE #4274: Regression on click on a simple element
## Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.14.0
* Platform / OS version: Debian (Dockerized in node:10-stretch-slim)
* URLs (if applicable): https://www.sisley-paris.com/en-GB/
* Node.js version: v10.15.1

**What steps will reproduce the problem?**

Open the website with a mobile emulation
Click on `#my_account_link`
Wait for the url `https://msecure.sisley-paris.com/en-GB/customer/account/login/`

_Please include code that reproduces the issue._
Note 1 : this code sample works fine until 1.5.0 of puppeteer and below
Note 2 : as a workaround changing the selector to `#my_account_link > i.icon-people` will make it works

```
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.setBypassCSP(true);
await page.emulate({viewport: { width: 375, height:  667, deviceScaleFactor: 2, isMobile: true, hasTouch: true, isLandscape: false}, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1'});
await page.goto('https://www.sisley-paris.com/en-GB/', {waitUntil: ['networkidle0', 'load', 'domcontentloaded'], timeout: 30000});

Promise.all([
  page.click('#my_account_link'),
  page.waitForNavigation( {waitUntil: ['networkidle0', 'load', 'domcontentloaded'], timeout: 30000})
]);
console.log(await page.url());
await page.screenshot({path: 'screenshot.png'});

await browser.close();
```

**What is the expected result?**
The page `https://msecure.sisley-paris.com/en-GB/customer/account/login/` should be opened when clicking on `#my_account_link`

**What happens instead?**
Browser is stuck on homepage

### PR DESCRIPTION
**Pull request by aslushnikov**
In certain cases inline element children might be positioned
outside of viewport.

In this case, we should intersect all content quads with viewport
before we pick one to click into.

Fixes #4274.

### CODE REVIEW

File: lib/JSHandle.js [hunk 1]
```diff
@@ -234,6 +238,19 @@ class ElementHandle extends JSHandle {
...
 
+  /**
+   * @param {!Array<{x: number, y: number}>} quad
+   * @param {number} width
+   * @param {number} height
+   * @return {!Array<{x: number, y: number}>}
+   */
+  _intersectQuadWithViewport(quad, width, height) {
+    return quad.map(point => ({
+      x: Math.min(Math.max(point.x, 0), width),
```
Comment (JoelEinbinder) [inline lib/JSHandle.js:249]: Nobody has added clamp to JavaScript yet? There’s probably an npm package for it :)

**Review by JoelEinbinder — APPROVED** [review]
