### PR TITLE
Carefully manage unhandled rejections for navigation

### LINKED ISSUE #738: Cant catch errors with .goto
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.10.2
* Platform / OS version: mac 10.12.6

**What steps will reproduce the problem?**
```
const puppeteer = require('puppeteer');

puppeteer.launch({ headless: false }).then(async function(browser) {

	const newPage = await browser.newPage();

	// newPage.goto('http://google.com', { timeout: 1 })
	// 	.catch(function(err) {});

	// newPage.goto('http://google.com', { timeout: 1 })
	// 	.then(function() {}, function(err) {});

	try {
		await newPage.goto('http://google.com', { timeout: 1 });
	} catch (e) {}
});
```

**What is the expected result?**
To be able to silence the error.

**What happens instead?**
The error isn't caught.
```
(node:33288) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 1ms exceeded
(node:33288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:33288) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

Listening to `unhandledRejection` on the process returns this:
```
Promise {
  <rejected> Error: Navigation Timeout Exceeded: 1ms exceeded
    at NavigatorWatcher.waitForNavigation (./node_modules/puppeteer/lib/NavigatorWatcher.js:74:13)
    at <anonymous> }
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Currently, navigation watcher throws exception if timeout
is exceeded.

Due to the way it is used in `page.navigate`, the promise
get's rejected before it is awaited, which is considered to
be "unhandled promise rejection".

Fixes #738

### CODE REVIEW

File: lib/Page.js [hunk 1]
```diff
@@ -375,8 +375,10 @@ class Page extends EventEmitter {
       watcher.cancel();
       throw e;
     }
-    await result;
+    const error = await result;
```
Comment (JoelEinbinder) [inline lib/Page.js]: Just for convention can result be something like navigationResultPromise? It is weird to say error = result.

**Review by JoelEinbinder — APPROVED** [review]

File: lib/Page.js (hunk 1 above)
Comment (aslushnikov) [reply lib/Page.js]: Done.
