### PR TITLE
fix: FirefoxLauncher should not use BrowserFetcher in puppeteer-core

### LINKED ISSUE #8919: [Bug]: Can't use `puppeteer-core` anymore due to error `_projectRoot is undefined. Unable to create a BrowserFetcher`
### Bug description

I am using Puppeteer within WebdriverIO to run commands through DevTools. Unfortunately it is not possible anymore to use `puppeteer-core` only as utility to launch browser (chrome and firefox). However [the docs](https://pptr.dev/#puppeteer-core) clearly suggest that this is still possible:

> When using puppeteer-core, remember to change the include line:
> 
> const puppeteer = require('puppeteer-core');
> 
> You will then need to call [puppeteer.connect](https://pptr.dev/api/puppeteer.puppeteer.connect) or [puppeteer.launch](https://pptr.dev/api/puppeteer.puppeteernode.launch) with an explicit executablePath or channel option.

Steps to reproduce the problem:

1. Create a new folder, e.g. `cd /tmp && mkdir pptrtest && cd pptrtest`
2. Install `puppeteer-core` via `npm i puppeteer-core`
3. Create the following script:

```js
const puppeteer = require('puppeteer-core');

(async () => {
    const pathToExtension = require('path').join(__dirname, 'my-extension');
    const browser = await puppeteer.launch({
        product: 'firefox',
        executablePath: '/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin',
        headless: true,
        defaultViewport: {
            width: 1200,
            height: 900
        }
    });
    await page.goto('https://webdriver.io');
    console.log(await page.title());
    // Test the background page as you would any other page.
    await browser.close();
})();
```

4. Run via `node test.js`

### Puppeteer version

latest

### Node.js version

18.6.0

### npm version

8.5.5

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:125
                throw new Error('_projectRoot is undefined. Unable to create a BrowserFetcher.');
                      ^

Error: _projectRoot is undefined. Unable to create a BrowserFetcher.
    at FirefoxLauncher._updateRevision (/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:125:23)
    at FirefoxLauncher.launch (/private/tmp/pptrcore/node_modules/puppeteer-core/lib/cjs/puppeteer/node/FirefoxLauncher.js:70:20)
    at async /private/tmp/pptrcore/test.js:5:21
```

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #8919

### CODE REVIEW

File: scripts/test-install.sh [hunk 1]
```diff
@@ -127,3 +127,31 @@ echo '{"type":"module"}' >>$TMPDIR/package.json
 npm install --loglevel silent "${tarball}"
 node --input-type="module" --eval="import puppeteer from 'puppeteer-core'"
 node --input-type="module" --eval="import 'puppeteer-core/lib/esm/puppeteer/revisions.js';"
+
+echo "Testing... Puppeteer Core launch with executablePath"
+TMPDIR="$(mktemp -d)"
+cd $TMPDIR
+echo '{"type":"module"}' >>$TMPDIR/package.json
```
Comment (thiagowfx) [inline scripts/test-install.sh]:
```suggestion
cd "$TMPDIR"
echo '{"type":"module"}' >> "$TMPDIR/package.json"
```

**Review by thiagowfx — APPROVED** [review]
