### PR TITLE
fix: emit all arguments from worker console logs

### LINKED ISSUE #2640: console message from Webworker receives only first argument
When using `page.on('console'...` on a console from a WebWorker, only first argument is printed.

In the following example, only 'a' will be logged:

```js
const puppeteer = require('puppeteer');
(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  page.on('console', message => console.log(message.text()));
  await page.setContent(`<!DOCTYPE html>
  <script id="worker1" type="javascript/worker">
    console.log('a', 'b'); //only 'a' will be logged
  </script>
  <script>
    const blob = new Blob([
      document.querySelector('#worker1').textContent
    ], { type: "text/javascript" })

    new Worker(window.URL.createObjectURL(blob));
  </script>`);
})()
```

### PR DESCRIPTION
**Pull request by JoelEinbinder**
Log.entryAdded doesn't report all the arguments from console logs. This PR switches to use Runtime.consoleAPICalled.

fixes #2640

### CODE REVIEW

File: lib/Worker.js [hunk 1]
```diff
@@ -21,23 +21,24 @@ class Worker extends EventEmitter {
   /**
    * @param {Puppeteer.CDPSession} client
    * @param {string} url
-   * @param {function(!Protocol.Log.entryAddedPayload)} logEntryAdded
+   * @param {function(!string, !Array<!JSHandle>)} consoleAPICalled
```
Comment (ebidel) [inline lib/Worker.js:24]: `!Array<!Puppeteer.JSHandle>`?

Comment (JoelEinbinder) [reply lib/Worker.js:24]: We haven't been using the Puppeteer. namespace when the type is included directly in the file.

Comment (ebidel) [reply lib/Worker.js:24]: Ack

**Review by ebidel — APPROVED** [review]
