### PR TITLE
fix: restore deferred promise debugging

### LINKED ISSUE #8832: [Bug]: "Waiting for target frame x failed" when crawling a lot of websites concurrently
### Bug description

Steps to reproduce the problem:

1. Do a lot at the same time (opening a lot of browsers and visiting pages etc.), causing Node to lag.
2. Observe an unhandledRejection like the following:
```
TimeoutError: Waiting for target frame 38DAB13DFEC9AD09315770D838D9F8C9 failed
    at Timeout._onTimeout (path\to\my_package\node_modules\puppeteer\src\util\DeferredPromise.ts:36:14)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

This is caused by the promise from [FrameManager.ts:153](https://github.com/puppeteer/puppeteer/blob/v16.2.0/src/common/FrameManager.ts#L153) not being fulfilled within 5 seconds (hardcoded in [DeferredPromise.ts](https://github.com/puppeteer/puppeteer/blob/v16.2.0/src/util/DeferredPromise.ts#L24)). If you add `if (isRejected) console.log('resolved anyway')` to [`resolve:` in DeferredPromise.ts](https://github.com/puppeteer/puppeteer/blob/v16.2.0/src/util/DeferredPromise.ts#L46) and set `process.on('uncaughtException', console.error)` then you can see that the promise will be resolved anyway later on.

I think the timeout should probably be configurable in some way (or removed entirely, but it probably serves a purpose).

### Puppeteer version

16.2.0

### Node.js version

18.7.0

### npm version

8.17.0

### What operating system are you seeing the problem on?

Windows

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by OrKoN**
Closes #8832

### CODE REVIEW

File: src/util/DebuggableDeferredPromise.ts [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+export function createDebuggableDeferredPromise<T>(
+  message: string
+): DeferredPromise<T> {
+  if (DEFERRED_PROMISE_DEBUG_TIMEOUT > 0) {
+    return createDeferredPromise({
+      message,
+      timeout: DEFERRED_PROMISE_DEBUG_TIMEOUT,
+    });
+  }
+  return createDeferredPromise();
```
Comment (sadym-chromium) [inline src/util/DebuggableDeferredPromise.ts:19]: Don't we want to keep the message for default timeout?
```suggestion
  return createDeferredPromise({message});
```

**Review by sadym-chromium — APPROVED** [review]
LGTM with a minor comment

File: src/util/DebuggableDeferredPromise.ts (hunk 1 above)
Comment (OrKoN) [reply src/util/DebuggableDeferredPromise.ts:19]: Nope, there should be no timeout and, thus, no message if it's not running the debug mode.
