### PR TITLE
fix: ensure existing targets are attached to pages

### LINKED ISSUE #12613: [Bug]: Not all frames are restored on reconnect
### Minimal, reproducible example

```TypeScript
it('should be able to reconnect to a disconnected browser (codesandbox)', async () => {
  const {puppeteer, browser, close} = await launch({});
  // Connection is closed on the original one
  let remoteClose!: () => Promise<void>;
  try {
    const browserWSEndpoint = browser.wsEndpoint();
    const page = await browser.newPage();
    await page.goto(
      'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html'
    );
    await new Promise(resolve => {
      return setTimeout(resolve, 11000);
    });
    const originalDump = await dumpFrames(page.mainFrame());
    await browser.disconnect();

    const remoteBrowser = await puppeteer.connect({
      browserWSEndpoint,
      protocol: browser.protocol,
    });
    remoteClose = remoteBrowser.close.bind(remoteBrowser);
    console.log(remoteClose);
    const pages = await remoteBrowser.pages();
    const restoredDump = await dumpFrames(pages[0]!.mainFrame());
    console.log(originalDump);
    console.log(restoredDump);
    expect(restoredDump).toEqual(originalDump);
  } finally {
    await remoteClose();
    await close();
  }
});
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

Not all frames are restored on reconnection

### Expectation

Restore all the frames

### Reality

The dump has missing frames

Original dump
```
[
  'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html',
  '    about:blank',
  '    https://nodebox-runtime.codesandbox.io/',
  '    https://worker.codesandbox.io/p/assets/webWorkerExtensionHostIframe-1633eaef.html?vscodeExtHostWorkerSrc=https%3A%2F%2Fworker.codesandbox.io%2Fp%2Fassets%2FextensionHost.worker-7fb0d9e8.js&parentOrigin=https%3A%2F%2Fcodesandbox.io&vscodeWebWorkerExtHostId=3c6542c7-fd18-4070-a40b-31843828b683',
  '    https://s8srw1.csb.app/',
  '        https://client-api.arkoselabs.com/v2/2.6.1/enforcement.bf6c920f19fb49ce16c82aaef4b83f45.html#11111111-1111-1111-1111-111111111111&26a71cac-f9bc-4d66-b762-5cdefac2d03f',
  '            https://client-api.arkoselabs.com/fc/assets/ec-game-core/game-core/1.22.0/standard/index.html?session=70317da269b3720d6.2399850801&r=us-east-1&meta=3&metabgclr=%23ffffff&metaiconclr=%23757575&guitextcolor=%23000000&pk=11111111-1111-1111-1111-111111111111&at=40&ag=101&cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc&lurl=https%3A%2F%2Faudio-us-east-1.arkoselabs.com&surl=https%3A%2F%2Fclient-api.arkoselabs.com&smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager&theme=default (game-core-frame)'
]
```

Dump on restored page

```
[
  'https://codesandbox.io/p/sandbox/funcaptcha-demo-s8srw1?file=%2Findex.html',
  '    about:blank',
  '    https://nodebox-runtime.codesandbox.io/',
  '    https://worker.codesandbox.io/p/assets/webWorkerExtensionHostIframe-1633eaef.html?vscodeExtHostWorkerSrc=https%3A%2F%2Fworker.codesandbox.io%2Fp%2Fassets%2FextensionHost.worker-7fb0d9e8.js&parentOrigin=https%3A%2F%2Fcodesandbox.io&vscodeWebWorkerExtHostId=3c6542c7-fd18-4070-a40b-31843828b683'
]
```

### Puppeteer configuration file (if used)

_No response_

### Puppeteer version

22.11.2

### Node version

20.10.0

### Package manager

npm

### Package manager version

10.2.3

### Operating system

macOS

### PR DESCRIPTION
**Pull request by OrKoN**
Closes https://github.com/puppeteer/puppeteer/issues/12613

### CODE REVIEW

File: packages/puppeteer-core/src/cdp/Page.ts [hunk 1]
```diff
@@ -299,6 +299,26 @@ export class CdpPage extends Page {
       .catch(debugError);
 
     this.#setupPrimaryTargetListeners();
+    this.#attachExistingTargets(this.#primaryTarget);
+  }
+
+  #attachExistingTargets(root: CdpTarget): void {
```
Comment (Lightning00Blade) [inline packages/puppeteer-core/src/cdp/Page.ts]: We don't use `root` anywhere else we should remove it and use `this` instead.

**Review by Lightning00Blade — APPROVED** [review]
LGTM + comment
