### PR TITLE
fix: support PlzNavigate in puppeteer.

### LINKED ISSUE #877: Adopt plznavigate in puppeteer
1. Recentrly, [plznavigate](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/sOs05JfmPFw) was enabled on Chromium Trunk. 
2. plznavigate changed protocol behavior in a few subtle ways that we relied upon in pptr
3. plznavigate causes a protocol bug that blocks our adoption
    - [crbug.com/767683](https://bugs.chromium.org/p/chromium/issues/detail?id=767683)
 

For the reference: a wip of pptr migration over to plznvigate: [aslushnikov/puppeteer:plznavigate](https://github.com/aslushnikov/puppeteer/tree/plznavigate)

The plan is to roll with `--disable-browser-side-navigation` flag passed over to launcher and
remove it as soon as the upstream is fixed.

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch migrates puppeteer to support PlzNavigate chromium
project.

As a consequence of this patch, we no longer wait for both
`requestWillBeSent` and `requestIntercepted` events to happen. This should
resolve a ton of request interception bugs that "hanged" the loading.

Fixes #877.

### CODE REVIEW

File: lib/NetworkManager.js [hunk 1]
```diff
@@ -179,30 +181,39 @@ class NetworkManager extends EventEmitter {
   }
 
   /**
-   * @param {string} requestId
+   * @param {?string} requestId
    * @param {string} interceptionId
```
Comment (JoelEinbinder) [inline lib/NetworkManager.js]: ?string

**Review by JoelEinbinder — APPROVED** [review]

File: lib/NetworkManager.js (hunk 1 above)
Comment (aslushnikov) [reply lib/NetworkManager.js]: Done.
