### PR TITLE
[fix] Launcher should handle chrome process errors

### LINKED ISSUE #750: Throw error with stack trace when launching with an invalid executablePath option
When `puppeteer` is used as a dependency or sub-dependency of another project that exposes the `puppeteer` API, an invalid `executablePath` option should be reported appropriately. Currently, if an invalid `executablePath` is provided to `puppeteer.launch(...)`, it is unclear where the actual error is coming from. It could be from any module. This error should be propagated with a stack trace directly from `puppeteer`. I have a fix for this and I will put up a PR momentarily.

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.11.0-alpha
* Platform / OS version: macOS 10.12.6

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1. `await puppeteer.launch({ executablePath: 'random-path' })`

**What is the expected result?**

An error containing a stack trace clearly describing the issue e.g.

```
Error: Error launching Chromium process with executable path "random-path"
    at fs.stat (/puppeteer/lib/Launcher.js:147:23)
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**What happens instead?**

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn random-path ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

### PR DESCRIPTION
**Pull request by aslushnikov**
Fixes #750

### CODE REVIEW

File: lib/Launcher.js [hunk 1]
```diff
@@ -165,7 +169,8 @@ function waitForWSEndpoint(chromeProcess, timeout) {
     const listeners = [
       helper.addEventListener(rl, 'line', onLine),
       helper.addEventListener(rl, 'close', onClose),
-      helper.addEventListener(chromeProcess, 'exit', onClose)
+      helper.addEventListener(chromeProcess, 'exit', onClose),
+      helper.addEventListener(chromeProcess, 'error', onClose)
```
Comment (JoelEinbinder) [inline lib/Launcher.js]: Can we log the error? It is helpful.

**Review by JoelEinbinder — APPROVED** [review]
