### PR TITLE
fix(Page.select): assert all values are of type "string".

### LINKED ISSUE #1276: page.select() should error if it can't find an option with requested value
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13-alpha
* Platform / OS version: macos

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
html:
```html
<html><body><select><option value="12"/></select></body</html>
```
puppeteer:
```js
page.select('select', 12)
```

**What is the expected result?**

Either select the option with the value that is string-equal to the second arg (0.12 behavior) OR throw an error when page.select cannot find a matching option.  The latter solution seems more generally useful.

**What happens instead?**
Select is blanked, no error is thrown

### PR DESCRIPTION
**Pull request by aslushnikov**
This patch starts asserting that all values are of type "string".

The alternative approach to cast values to strings
might yield a hard-to-debug errors.

Fixes #1276.

### CODE REVIEW

**Comment by JoelEinbinder** [comment]
I think we should coerce to strings. That's what `<select>` does.

**Comment by aslushnikov** [comment]
Implicit typecasting is unpredictable at times.

We don't save much in terms of usability, so I prefer a strict API that will simplify debugging story.

**Review by JoelEinbinder — APPROVED** [review]

File: test/test.js [hunk 1]
```diff
@@ -2737,69 +2737,69 @@ describe('Page', function() {
...
       const result = await page.select('select','42','blue','black','magenta');
       expect(result.length).toEqual(1);
     }));
-
     it('should return [] on no values',SX(async function() {
       await page.goto(PREFIX + '/input/select.html');
       const result = await page.select('select');
       expect(result).toEqual([]);
     }));
-
```
Comment (JoelEinbinder) [inline test/test.js:2787]: What happened to my newlines?

Comment (aslushnikov) [reply test/test.js:2787]: We don't have newlines between "it" tests, do we?
