### PR TITLE
fix: remove boundary conditions for visibility

### LINKED ISSUE #9232: [Bug]: waitForSelector doesn't consider elements above current viewport as "visible"
### Bug description

#8954 changed waitForSelector "visible" flag behavior to consider only elements inside the current viewport as visible. This was reverted in #9087, but it looks like the revert wasn't complete. Apparently elements below the current viewport are now considered "visible", but not elements above (or left) of the current viewport.

Simple script to reproduce (works with 17.1.3, fails with 19.2.2):

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.setViewport({width: 800, height: 600});
  await page.setContent(`
    <html><body>
    <button id="button1">Button 1</button>
    <div id="content" style="height: 2000px;"></div>
    <button id="button2">Button 2</button>
    </body></html>
  `);
  await page.waitForSelector('#button1', {visible: true});
  await page.waitForSelector('#button2', {visible: true});
  console.log('ok, both buttons are visible');
  await page.evaluate(() => window.button2.scrollIntoView());
  await page.waitForSelector('#button1', {visible: true});
  console.log('ok, button1 still visible (although outside viewport)');
  await browser.close();
})();
```

### Puppeteer version

19.2.2

### Node.js version

16.18.0

### npm version

8.19.2

### What operating system are you seeing the problem on?

macOS

### Configuration file

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jrandolf-google**
Fixed: https://github.com/puppeteer/puppeteer/issues/9232

### CODE REVIEW

**Review by OrKoN — APPROVED** [review]

File: packages/puppeteer-core/src/injected/util.ts [hunk 1]
```diff
@@ -64,5 +64,5 @@ export const checkVisibility = (
 
 function isBoundingBoxVisible(element: Element): boolean {
```
Comment (OrKoN) [inline packages/puppeteer-core/src/injected/util.ts]: nit: rename isBoundingBoxVisible to something that does not have word Visible in it?
