### PR TITLE
fix: Inherit browser-level proxy settings from incognito context

### LINKED ISSUE #7589: [Bug]: Puppeteer 10.4.0 ignores the proxy-server launch argument
### Bug description

Steps to reproduce the problem:

1. Install 10.4.0
2. Run this script, which sets a non-existent proxy server:

```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({
    args: [ '--proxy-server=http://non-existent-domain:8000' ]
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.screenshot({ path: 'example.png' });

  await browser.close();
})();
```

Earlier versions will fail (correctly!) because the proxy server is not there.  10.4.0 ignores the proxy setting and runs as if the setting was not there.

### Puppeteer version

10.4.0

### Node.js version

16.8.0

### npm version

7.21.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by jimmydief**
**What kind of change does this PR introduce?**

This fixes #7589 which was a regression caused by #7516 and released in 10.4.0. It closes #7677 which fixed part of the issue but did not cover the proxy bypass list and also did not include tests.

**Did you add tests for your changes?**

Yes.

**If relevant, did you update the documentation?**

N/A

**Summary**

Browser-level proxy settings are now once again respected when creating new incognito browser contexts. Browser-level settings can be overridden at the context level. Tests were added for request proxy behavior in general.

**Does this PR introduce a breaking change?**

Nope.

**Other information**

N/A

### CODE REVIEW

File: src/common/Browser.ts [hunk 1]
```diff
@@ -319,7 +319,7 @@ export class Browser extends EventEmitter {
   async createIncognitoBrowserContext(
     options: BrowserContextOptions = {}
   ): Promise<BrowserContext> {
-    const { proxyServer = '', proxyBypassList = [] } = options;
+    const { proxyServer, proxyBypassList } = options;
```
Comment (jimmydief) [inline src/common/Browser.ts:322]: Omitting the defaults here causes the browser-level settings to be respected if these aren't provided.

File: test/proxy.spec.ts [hunk 2]
```diff
@@ -0,0 +1,205 @@
...
+
+    proxyServer = http
+      .createServer(
+        (
+          originalRequest: IncomingMessage,
+          originalResponse: ServerResponse
+        ) => {
+          proxiedRequestUrls.push(originalRequest.url as string);
+
+          const proxyRequest = http.request(
```
Comment (jimmydief) [inline test/proxy.spec.ts:58]: Creating a simple proxy server which forwards requests on to the `TestServer`.

**Comment by iJoris** [comment]
You are missing the cla
https://github.com/puppeteer/puppeteer/blob/7c0a7b92cf98033425b78e1e7a96bb440a636123/CONTRIBUTING.md#contributor-license-agreement

**Comment by jimmydief** [comment]
> You are missing the cla https://github.com/puppeteer/puppeteer/blob/7c0a7b92cf98033425b78e1e7a96bb440a636123/CONTRIBUTING.md#contributor-license-agreement

Screen Shot 2021-11-15 at 9 55 58 AM

Signed it after opening the PR, seems like updating the status check might require some manual step.

**Comment by Momotoculteur** [comment]
Hello guys :) 

Any news from this PR ? I need it for my project, i cannot upgrade anymore then my pptr version.

Thank in advance,
Bastien

**Review by iJoris — APPROVED** [review]

**Comment by Niek** [comment]
Ping @OrKoN @nschonni

**Review by OrKoN — CHANGES_REQUESTED** [review]
I think the new tests will be failing in Firefox as expected. Could you please add `itFailsFirefox` instead of `it` for those tests?

**Comment by jimmydief** [comment]
@OrKoN The test failure on Windows actually seems to be pointing out the issue reported in #7873, #7719, and #7698. I put it behind `itFailsWindows` for now and left a comment referring to those issues.

**Comment by iJoris** [comment]
@jimmydief, closed that issue already. 

If you need testing on windows, hit me up.

**Comment by jimmydief** [comment]
> @jimmydief, closed that issue already.
> 
> If you need testing on windows, hit me up.

@iJoris Gotcha, thanks. The only test that was failing was related to `createIncognitoBrowserContext` with the `proxyServer` argument provided. Could you confirm whether the example from #7698 fails on your Windows machine?

**Comment by iJoris** [comment]
> > @jimmydief, closed that issue already.
> > If you need testing on windows, hit me up.
> 
> @iJoris Gotcha, thanks. The only test that was failing was related to `createIncognitoBrowserContext` with the `proxyServer` argument provided. Could you confirm whether the example from #7698 fails on your Windows machine?
Hi,

I can confirm that the proxy server and an createIncognitoBrowserContext do not work after 10.2. Seems that the proxyServer gets ignored in an incognitoBrowserContext.

I thought that this PR would resolve this issue tho? Otherwise, I create my own issue.
https://github.com/puppeteer/puppeteer/issues/7873 is the same problem.

https://github.com/puppeteer/puppeteer/issues/7589#issuecomment-927182049

**Review by OrKoN — APPROVED** [review]

**Comment by iJoris** [comment]
Ping @nschonni @jrandolf
