### PR TITLE
fix(page): teach page.click() to click partially offscreen buttons

### LINKED ISSUE #2804: click does not fire.
**Tell us about your environment:**

* Puppeteer version: 1.5.0
* Platform / OS version: mac OSX 10.13.5
* URLs (if applicable):
* Node.js version: 8.11.3

**What steps will reproduce the problem?**

I tried the following code. but click event does not fire.

  const browser = await puppeteer.launch({
    headless: false,
    slowMo: 450
  }); 
  const page = await browser.newPage()
  await page.goto('https://www.yahoo.co.jp/')
  await page.click('.Util-textBold > a')
  await page.type('#username', 'test_user')
  await page.click('#btnNext')

// also I tried
// await page.click('button[type="submit"]')

**What is the expected result?**

click a '#btnNext'

**What happens instead?**
nothing happens.

### PR DESCRIPTION
**Pull request by aslushnikov**
Originally, we use `Element.scrollIntoViewIfNeeded` to make sure
button is on screen before trying to click it.

However, `Element.scrollIntoViewIfNeeded` doesn't work in certain
scenarios, e.g. when element is partially visible and horizontal
scrolling is required to make it fully visible.

This patch polyfills `element.scrollIntoViewIfNeeded` using
IntersectionObserver and `Element.scrollIntoView`.

Fixes #2804.

### CODE REVIEW

File: lib/ElementHandle.js [hunk 1]
```diff
@@ -55,12 +55,20 @@ class ElementHandle extends JSHandle {
...
         return 'Node is not of type HTMLElement';
-      element.scrollIntoViewIfNeeded();
+      const visibleRatio = await new Promise(resolve => {
+        const observer = new IntersectionObserver(entries => {
+          resolve(entries[0].intersectionRatio);
+          observer.disconnect();
+        });
+        observer.observe(element);
+      });
+      if (Math.abs(visibleRatio - 1.0) > 1e-3)
```
Comment (JoelEinbinder) [inline lib/ElementHandle.js]: 1e-3 is scary. Lets just compare to 1

**Review by JoelEinbinder — APPROVED** [review]

**Comment by transitive-bullshit** [comment]
Just wanted to say that it's an amazing feeling to run into an issue, track it down, and find out it's already been solved!

Keep up the great work, guys!! @aslushnikov @JoelEinbinder 💯
