### PR TITLE
fix(puppeteer-core): avoid type instantiation errors

### LINKED ISSUE #9369: [Bug]: Type error: Type instantiation is excessively deep and possibly infinite.
### Bug description

Steps to reproduce the problem:

1. Query a complex selector in a Typescript puppeteer test script
2. Typescript complains that resolving the return type takes too many steps: `Type error: Type instantiation is excessively deep and possibly infinite.`

### Puppeteer version

19.3.0

### Node.js version

16.18.1

### npm version

yarn 1.22.19

### What operating system are you seeing the problem on?

Linux

### Configuration file

_No response_

### Relevant log output

```Shell
Type error: Type instantiation is excessively deep and possibly infinite.

  70 | 
> 71 |     const rows = await page.$$( "[data-testid=\"my-component\"] tbody tr" )
     |                        ^
```

### PR DESCRIPTION
**Pull request by OrKoN**
Using the accumulator allows enabling the tail-recursion optimization in the TypeScript compiler.

Closes #9369

### CODE REVIEW

**Comment by OrKoN** [comment]
cc @gomain

**Review by Lightning00Blade — APPROVED** [review]

File: packages/puppeteer-core/src/common/types.ts [hunk 1]
```diff
@@ -135,32 +135,36 @@ type BeginSubclassSelectorTokens = ['.', '#', '[', ':'];
...
-      : never
-    : never
-  : [];
+      ? FlatmapSplitWithDelemiters<
+          RestInputs,
+          Delemiters,
+          [...Acc, ...SplitWithDelemiters<FirstInput, Delemiters>]
+        >
+      : Acc
+    : Acc
```
Comment (gomain) [inline packages/puppeteer-core/src/common/types.ts:161]: These two branches are `never` taken.

**Review by gomain — COMMENTED** [review]
A bit late to the party, but here goes...

Spotted a minor imperfection, where a couple evaluation branches should be marked as `never`.

The `Acc` trick does not allow tail recursion optimization (I believe there is no such optimization). It does allow intermediate thunks to be evaluated before the recursive call. This hugely reduces the (virtual) stack size. There still exists a limit on how many tokens the input string can contain before instantiation depth exceeds the limit. From [trial and error investigation](https://github.com/gomain/puppeteer/blob/d3326ed2aef912b9d6ee7cd4e9355acc326a2d34/packages/puppeteer-core/src/common/types.ts#L172) it seems the recursion depth limit is about 1000 (typescript v4.5.4).

Practically, a selector string with multiple compound selectors with explicit combinators (i.e. not space), such as `"div > div > div > ..."` would be limited to ~500 compound selectors. We could probably live with that.

**Comment by gomain** [comment]
@OrKoN https://github.com/microsoft/TypeScript/pull/45711/files#diff-d9ab6589e714c71e657f601cf30ff51dfc607fc98419bf72e04f6b0fa92cc4b8R15233-R15237
