### PR TITLE
fix: fallback to CSS

### LINKED ISSUE #9828: [Bug]: Error with selector including `:not()`
### Bug expectation

I expect the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` to select all elements with a `'data-test-id'` attribute starting with "test-", except for those with the suffix "-foo".

Since updating to Puppeteer-core 19.7.3, the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` is no longer recognized as a valid selector, and I receive the following error message:
```
Error: Evaluation failed: Error: [data-test-id^="test-"]:not([data-test-id^="test-foo"]) is not a valid selector: Unexpected sequence
```

Downgrading to version 19.7.2 of Puppeteer allows the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` to function as expected

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch();
  const page = await browser.newPage();

  await page.goto('https://example.com');

  await page.$$(
    '[data-test-id^="test-"]:not([data-test-id^="test-foo"])',
  );

  await browser.close();
})();
```

### Error string

`Error: Evaluation failed: Error: [data-test-id^="test-"]:not([data-test-id^="test-foo"]) is not a valid selector: Unexpected sequence )`

### Puppeteer configuration

_No response_

### Puppeteer version

19.7.3

### Node version

18.13.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

### PR DESCRIPTION
**Pull request by jrandolf-google**
Fixed: #9828

### CODE REVIEW

File: packages/puppeteer-core/src/injected/PSelectorParser.ts [hunk 1]
```diff
@@ -51,69 +51,74 @@ const unquote = (text: string): string => {
...
-  }
-  if (storage.length) {
-    compoundSelector.push(stringify(storage));
+    if (storage.length) {
+      compoundSelector.push(stringify(storage));
+    }
+    return [selectors, isPureCSS];
+  } catch {
+    // In case parsing breaks, we fallback to CSS.
+    return [[], true];
```
Comment (OrKoN) [inline packages/puppeteer-core/src/injected/PSelectorParser.ts]: Let's do the try/catch on the consumer side. I don't think p-selectors should be concerned with fallbacks and know about CSS.

Comment (jrandolf) [reply packages/puppeteer-core/src/injected/PSelectorParser.ts]: SGTM

**Review by OrKoN — APPROVED** [review]
